/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicImport } from './routes/__public'
import { Route as authImport } from './routes/__auth'
import { Route as authIndexImport } from './routes/__auth.index'

// Create Virtual Routes

const publicLoginLazyImport = createFileRoute('/__public/login')()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/__public',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/__auth',
  getParentRoute: () => rootRoute,
} as any)

const authIndexRoute = authIndexImport.update({
  path: '/',
  getParentRoute: () => authRoute,
} as any)

const publicLoginLazyRoute = publicLoginLazyImport
  .update({
    path: '/login',
    getParentRoute: () => publicRoute,
  } as any)
  .lazy(() => import('./routes/__public.login.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__auth': {
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/__public': {
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/__public/login': {
      preLoaderRoute: typeof publicLoginLazyImport
      parentRoute: typeof publicImport
    }
    '/__auth/': {
      preLoaderRoute: typeof authIndexImport
      parentRoute: typeof authImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  authRoute.addChildren([authIndexRoute]),
  publicRoute.addChildren([publicLoginLazyRoute]),
])

/* prettier-ignore-end */
