/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicImport } from './routes/__public'
import { Route as authImport } from './routes/__auth'
import { Route as authIndexImport } from './routes/__auth.index'
import { Route as authTasksImport } from './routes/__auth.tasks'

// Create Virtual Routes

const publicRegisterLazyImport = createFileRoute('/__public/register')()
const publicLoginLazyImport = createFileRoute('/__public/login')()
const authNotesCreateLazyImport = createFileRoute('/__auth/notes/create')()
const authNotesIdLazyImport = createFileRoute('/__auth/notes/$id')()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/__public',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/__auth',
  getParentRoute: () => rootRoute,
} as any)

const authIndexRoute = authIndexImport.update({
  path: '/',
  getParentRoute: () => authRoute,
} as any)

const publicRegisterLazyRoute = publicRegisterLazyImport
  .update({
    path: '/register',
    getParentRoute: () => publicRoute,
  } as any)
  .lazy(() => import('./routes/__public.register.lazy').then((d) => d.Route))

const publicLoginLazyRoute = publicLoginLazyImport
  .update({
    path: '/login',
    getParentRoute: () => publicRoute,
  } as any)
  .lazy(() => import('./routes/__public.login.lazy').then((d) => d.Route))

const authTasksRoute = authTasksImport.update({
  path: '/tasks',
  getParentRoute: () => authRoute,
} as any)

const authNotesCreateLazyRoute = authNotesCreateLazyImport
  .update({
    path: '/notes/create',
    getParentRoute: () => authRoute,
  } as any)
  .lazy(() => import('./routes/__auth.notes.create.lazy').then((d) => d.Route))

const authNotesIdLazyRoute = authNotesIdLazyImport
  .update({
    path: '/notes/$id',
    getParentRoute: () => authRoute,
  } as any)
  .lazy(() => import('./routes/__auth.notes.$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__auth': {
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/__public': {
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/__auth/tasks': {
      preLoaderRoute: typeof authTasksImport
      parentRoute: typeof authImport
    }
    '/__public/login': {
      preLoaderRoute: typeof publicLoginLazyImport
      parentRoute: typeof publicImport
    }
    '/__public/register': {
      preLoaderRoute: typeof publicRegisterLazyImport
      parentRoute: typeof publicImport
    }
    '/__auth/': {
      preLoaderRoute: typeof authIndexImport
      parentRoute: typeof authImport
    }
    '/__auth/notes/$id': {
      preLoaderRoute: typeof authNotesIdLazyImport
      parentRoute: typeof authImport
    }
    '/__auth/notes/create': {
      preLoaderRoute: typeof authNotesCreateLazyImport
      parentRoute: typeof authImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  authRoute.addChildren([
    authTasksRoute,
    authIndexRoute,
    authNotesIdLazyRoute,
    authNotesCreateLazyRoute,
  ]),
  publicRoute.addChildren([publicLoginLazyRoute, publicRegisterLazyRoute]),
])

/* prettier-ignore-end */
